name: "Dev Deploy"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::515503358443:oidc-provider/token.actions.githubusercontent.com"
      aws-region: us-east-1
      aws-statefile-s3-bucket: "diegosantosouza-us-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "diegosantosouza-us-east-1-terraform-lock"
